# Site settings
title: DEVLOG
email: unchai@protonmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.tolinezip.com" # the base hostname & protocol for your site
github_username: unchai
twitter_username: unchai_dev

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - .nojekyll
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.cofee"
